export const UPDATE_PERSONAL_BETS = 'UPDATE_PERSONAL_BETS';
export const UPDATE_FRIENDS_BETS = 'UPDATE_FRIENDS_BETS';
export const UPDATE_PROFILE_PIC = 'UPDATE_PROFILE_PIC';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';